### ISSUE TITLE
npm start looks like not working

### ISSUE THREAD

**Issue by bruk1977** [songawee/angular2_code_splitting#11]
HI, 

Thanks for the great sample... after 'npm start' loading localhost:3011 gives a blank page... I'm getting 404 error on console for the following js. 

http://localhost:3011/js/main.js 404 (Not Found)

Any idea to fix?

Thanks

**Comment by dennis-johnson-dev** [comment]
My first thought is you might have to kick off a build - `npm run build`. If you've done that, can you verify that there are files located at `<project-root>/public/js`?

Thanks

**Comment by bruk1977** [comment]
Thanks @songawee yea 'npm run build' had an issue... removing 'node_modules', reinstalling npm and running again 'npm run build' fixes the issue...

**Comment by dennis-johnson-dev** [comment]
Glad you got it worked out. let me know if you need anything else!

Cheers
