### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by bruk1977** [songawee/angular2_code_splitting#12]
Hi @songawee 

I love this sample code. :-) One thing, have you run in IE? I'm getting a blank page without any error in console in IE11.

system.import transpilation issue may be?

Thanks,
Bruk

**Comment by dennis-johnson-dev** [comment]
@bruk1977 Good catch. Yeah, I forgot to add a Promise polyfill which is my guess to the issue you're seeing. I haven't verified IE 11 support, but this should fix it. If you continue to experience the issue, let me know and I can find an IE vm and debug from there.

You'll just need to re-run the build and restart the app and hopefully you're good to go 👍
